# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 895a4129f9680047fa906cae4bcda47df26be42967201ac390246355959b58364ae0a96628854a01944739d830476f70c8ede9d28a5d06a2e34eb1f1b023aa96

test:
  secret_key_base: b9613f23e7b47f9577a0cad31149b0c2324491bac84686c4cef7862ddbac350cf499f9fa82d9b030997103b252a1c08917973b822f974863b02def8d1d56980e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
